config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :comments
  get 'friends/index'
  get 'friends/destroy'
  resources :friends, only: [:index, :create, :destroy]
  resources :user_posts
  resources :friend_requests do
    member do
      post :accept
      post :reject
    end
  end
  resources :user_posts do
    resources :comments
    resources :likes
  end
  match 'users/:id' => 'users#show', :as => :user, :via => :get
  match 'pending_requests' => 'friend_requests#index', :as => :pending_requests, :via => :get
  get 'all_users' => 'users#all_other_users'
  get 'search_users' => 'users#search'
  # edit user profile
  # match 'users/edit/:id' => 'users#edit', :as => :edit_profile, :via => :get

  # match 'friends' => 'friends#index', :as => :friends, :via => :get

  root 'user_posts#index'
end

app/models/user_post.rb
class UserPost < ApplicationRecord
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image
end

app/controllers/user_posts_controller.rb
class UserPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_post, only: %i[ show edit update destroy ]

  # GET /user_posts or /user_posts.json
  def index
    @user_posts = current_user.user_posts.all.order(created_at: :desc)
    @user_post = UserPost.new

    @friends = current_user.friends.pluck(:id)
    @friends_posts = UserPost.where(user_id: @friends).order(created_at: :desc)
    @combined_posts = current_user.user_posts + @friends_posts.each { |post| post }
    @sorted_posts = @combined_posts.sort_by(&:created_at).reverse
  end

  # GET /user_posts/1 or /user_posts/1.json
  def show
    @comments = Comment.where(user_post_id: @user_post.id).order(created_at: :desc)
    @user_post = UserPost.find(params[:id])
    if @user_post.nil?
      flash[:error] = "Post not found or doesn't exist"
      redirect_to root_path
    else
      render :show
    end
  end

  # GET /user_posts/new
  def new
    @user_post = current_user.user_posts.build
  end

  # GET /user_posts/1/edit
  def edit
  end

  # POST /user_posts or /user_posts.json
  def create
    @user_post = current_user.user_posts.build(user_post_params)

    respond_to do |format|
      if @user_post.save
        format.html { redirect_back fallback_location: root_path, notice: "User post was successfully created." }
        format.json { render :show, status: :created, location: @user_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_posts/1 or /user_posts/1.json
  def update
    respond_to do |format|
      if @user_post.update(user_post_params)
        format.html { redirect_back fallback_location: root_path, notice: "User post was successfully updated." }
        format.json { render :show, status: :ok, location: @user_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_posts/1 or /user_posts/1.json
  def destroy
    @user_post.destroy
    respond_to do |format|
      format.html { redirect_to user_posts_url, notice: "User post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_post
      @user_post = UserPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_post_params
      params.require(:user_post).permit(:message, :image)
    end
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/views/user_posts/_comments.html.erb
<% pre_like = @user_post.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= button_to 'Unlike', user_post_like_path(@user_post.id, pre_like), method: :delete, class: "button is-success" %>
  <% else %>
    <%= button_to 'Like', user_post_likes_path(@user_post.id), method: :post, class: "button is-warning post-link" %>
  <% end %>
    <% if @user_post.user_id == current_user.id %>
      <%= link_to 'edit', edit_user_post_path(@user_post.id), class: "far fa-edit post-link" %>
      <%= link_to 'delete', user_post_path(@user_post.id), method: :delete, class: "far fa-trash-alt post-link" %>
<% end %>

app/views/user_posts/_feed.html.erb
<% @sorted_posts.each do |f|%>
  <div class="message">
    <div class="message-header">
      <div class="message-header-title">
        <%= f.user.name %>
      </div>
      <div class="message-header-date">
        <%= f.created_at.strftime("%Y-%m-%d") %>
      </div>
    </div>
    <div class="message-body">
      <%= f.message %>
      <% if f.image.attached? %>
        <%= image_tag f.image, style: "width: 100%; display: block;"%>
      <% end %>
    </div>
    <div class="message-likes">
      <div class='post-buttons'>
        <% pre_like = f.likes.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
          <%= link_to 'Unlike', user_post_like_path(f.id, pre_like), method: :delete, class: "button is-success post-link" %>
        <% else %>
          <%= link_to 'Like', user_post_likes_path(f.id), method: :post, class: "button is-warning post-link" %>
        <% end %>
        <%= link_to 'comments', user_post_path(f.id), class: "button is-link post-link" %>
        <% if f.user_id == current_user.id%>
          <%= link_to 'edit', edit_user_post_path(f.id), class: "far fa-edit post-link" %>
          <%= link_to 'delete', user_post_path(f.id), method: :delete, class: "far fa-trash-alt post-link" %>
        <% end %>
      </div>
      <div class='post-stats'>
        <p class="likes-count"><%= f.likes.count %> <%= (f.likes.count) <= 1 ? 'Like' : 'Likes'%></p>
        <p class='comments-count'><%= f.comments.count %> <%= (f.comments.count) <= 1 ? "Comment" : "Comments" %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/user_posts/_form.html.erb
<%= simple_form_for(@user_post) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :message, label: false, input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label"}, placeholder: "What's on your mind?", autofocus: true %>
      <%= f.file_field :image %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-warning" %>
<% end %>

app/views/user_posts/_friend_suggestions.html.erb
<p class='right-bar-title'>Friend Suggestions</p>
<% suggestions = User.where.not(id: current_user.friends.ids + [current_user.id]).order("Random()").limit(3) %>

<% if suggestions.any? %>
  <% suggestions.each do |user|  %>
    <div class="friend-choices">
      <div class='avatar-name'>
        <span class='friend-sug friend-avatar'><%= image_tag user.avatar_thumbnail, class: 'avatar friend_avatar' %></span>
        <span class='friend-sug friend-name'><%= link_to user.name, user_path(user) %></span>
      </div>
      <div class='add-button'>
        <span class='friend-sug friend-add'><%= link_to '+', friend_requests_path(friend_id: user.id), method: :post %> </span>
      </div>
    </div>
  <% end %>
<% else %>
  <p class='no-friends'>No suggestions</p>
<% end %>

app/views/user_posts/_left_bar.html.erb
<div class='avatar'>
  <%= image_tag current_user.avatar_thumbnail, class: 'avatar user_avatar' %>
</div>
<div class='right-bar-links'>
  <p class='username'><%= current_user.name %></p>
  <p class='username'>@<%= current_user.username %></p>
  <ul>
    <%# Feed root path %>
    <p class='left-bar-link'><li><%= link_to 'Feed', root_path, class: 'left-link' %></li></p>
    <p class='left-bar-link'><li><%= link_to 'Profile', user_path(current_user), class: 'left-link' %></li></p>
    <p class='left-bar-link'><li><%= link_to 'Friends', friends_path(current_user), class: 'left-link' %></li></p>
    <p class='left-bar-link'><li><%= link_to 'Pending Requests', pending_requests_path(current_user), class: 'left-link' %></li></p>
    <p class='left-bar-link'><li><%= link_to 'All Users', all_users_path, class: 'left-link' %></li></p>
    <p class='left-bar-link'><li><%= link_to 'Settings', edit_user_registration_path(current_user), class: 'left-link' %></li></p>
    <p class='left-bar-link'><li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'left-link' %></li></p>
  </ul>
</div>

app/views/user_posts/_right_bar_friends.html.erb
<p class='right-bar-title friends-right-bar'>Friends</p>
<% friends = current_user.friends.order("Random()").limit(3) %>

<% friends.each do |user|  %>
  <div class="friend-choices">
    <div class='avatar-name'>
      <span class='friend-sug friend-avatar'><%= image_tag user.avatar_thumbnail, class: 'avatar friend_avatar' %></span>
      <span class='friend-sug friend-name'><%= link_to user.name, user_path(user) %></span>
    </div>
    <div class='add-button'>
      <span class='friend-sug friend-add'><%= link_to '-', friends_destroy_path(friend: user.id), method: :delete %> </span>
    </div>
  </div>
<% end %>

app/views/user_posts/_show_message.html.erb
<div class="message-container show-container">
  <div class="message show-message">
    <div class="message-header show-header">
      <div class="message-header-title show-title">
        <%= @user_post.user.name %>
      </div>
      <div class="message-header-date show-date">
        <%= @user_post.created_at %>
      </div>
    </div>
    <div class="message-body show-body">
      <%= @user_post.message %>
    </div>
    <div class="message-likes show-likes">
      <div class='post-buttons show-buttons'>
        <%= render 'comments' %>
      </div>
      <p class="likes-count"><%= @user_post.likes.count %> <%= (@user_post.likes.count) <= 1 ? 'Like' : 'Likes'%></p>
    </div>
  </div>
  <h2 class='show-comment-title'>Comments</h2>
  <div class='show-comments'>
    <% @comments.each do |comment| %>
      <div class='comment-container'>
        <div class='message-header comment-header'>
          <div class='comment-header-title'>
            <%= User.find(comment.user_id).name %>
          </div>
          <div class='comment-header-date'>
            <%= comment.created_at.strftime("%Y-%m-%d") %>
          </div>
        </div>
        <div class='message-body comment-body'>
          <%= comment.message %>
        </div>
        <div class='comment-buttons'>
          <% if comment.user_id == current_user.id %>
            <%= link_to 'Edit', edit_comment_path(comment.id, user_post_id: comment.user_post_id) %>
            <%= link_to 'delete', user_post_comment_path(comment.id, user_post_id: comment.user_post_id), method: :delete %>
          <% end %>
          <% if @user_post.user_id == current_user.id && comment.user_id != current_user.id %>
            <%= link_to 'delete', user_post_comment_path(comment.id, user_post_id: comment.user_post_id), method: :delete %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/user_posts/edit.html.erb
<h1>Editing User Post</h1>

<%= render 'form', user_post: @user_post %>

<%= link_to 'Show', @user_post %> |
<%= link_to 'Back', user_posts_path %>

app/views/user_posts/index.html.erb
<div class="container">
  <div class="column side-bar left-column">
    <%= render 'left_bar' %>
  </div>
  <div class="column message-feed center-column">
    <div class="message">
      <%= render 'form', user_post: @user_post %>
    </div>
    <div class="feed front-feed">
      <%= render 'feed', user_post: @user_post %>
    </div>
  </div>
  <div class="column right-bar right-column">
    <div class='friend-suggs'>
      <%= render 'friend_suggestions' %>
    </div>
    <div class='friends'>
      <%= render 'right_bar_friends' %>
    </div>
  </div>
</div>

app/views/user_posts/new.html.erb
<h1>New User Post</h1>

<%= render 'form', user_post: @user_post %>

<%= link_to 'Back', user_posts_path %>

app/views/user_posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class='container'>
  <div class="column side-bar left-column">
    <%= render 'left_bar' %>
  </div>
  <div id='show-mid-col', class="column message-feed center-column">
    <%= render 'show_message'%>
    <%= render 'comments/form' %>
  </div>
  <div class="column right-bar right-column">
    <div class='friend-suggs'>
      <%= render 'friend_suggestions' %>
    </div>
    <div class='friends'>
      <%= render 'right_bar_friends' %>
    </div>
  </div>
</div>