config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :comments
  get 'friends/index'
  get 'friends/destroy'
  resources :friends, only: [:index, :create, :destroy]
  resources :user_posts
  resources :friend_requests do
    member do
      post :accept
      post :reject
    end
  end
  resources :user_posts do
    resources :comments
    resources :likes
  end
  match 'users/:id' => 'users#show', :as => :user, :via => :get
  match 'pending_requests' => 'friend_requests#index', :as => :pending_requests, :via => :get
  get 'all_users' => 'users#all_other_users'
  get 'search_users' => 'users#search'
  # edit user profile
  # match 'users/edit/:id' => 'users#edit', :as => :edit_profile, :via => :get

  # match 'friends' => 'friends#index', :as => :friends, :via => :get

  root 'user_posts#index'
end

app/models/user.rb
class User < ApplicationRecord
  after_commit :add_default_avatar, on: [:create, :update]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook]

  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  validates :blood_type, length: { maximum: 3 }

  has_many :friend_requests, dependent: :destroy, foreign_key: :user_id
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :user_posts
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar
  validate :acceptable_avatar

  def self.from_omniauth(auth)
    name = auth.info.name
    user = User.where(email: auth.info.email).first
    user ||= User.create!(provider: auth.provider, uid: auth.uid, name: name, username: auth.info.name, email: auth.info.email,password: Devise.friendly_token[0, 20])
      user
  end

  def acceptable_avatar
    return unless avatar.attached?

    unless avatar.blob.byte_size <= 5.megabytes
      errors.add(:avatar, "is too large")
    end

    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(avatar.content_type)
      errors.add(:avatar, "must be a JPEG or PNG")
    end
  end


  def avatar_thumbnail
    # error handle
    begin
      if avatar.attached?
        avatar.variant(resize: '300x300!').processed
      else
        '/default_profile.jpg'
      end 
    rescue => exception
      exception.message
    end
  end

  def remove_friend(friend)
    current_user.friends.destroy(friend)
  end

  private

  def add_default_avatar
    unless avatar.attached?
      avatar.attach(io: File.open('app/assets/images/default_profile.jpg'), filename: 'default_profile.jpg', content_type: 'image/jpg')
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :facebook
  
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  after_action :set_avatar, :send_welcome_email, :create_friend_invitations, only: :create, if: -> { @user.persisted? }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user_posts = UserPost.where(user_id: params[:id]).all
    @user = User.find(params[:id])
  end

  def all_other_users
    @everyone_else = User.all.where.not(id: current_user.id)
  end

  def search
    @query = params[:query].downcase
    @searched_users = User.where("LOWER(name) LIKE ?", "%#{@query}%").order(:name)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :blood_type, :education, :username)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_everyone_else.html.erb
<div class='users-container'>
  <% @everyone_else.each do |f| %>
    <div class='pending-user friend-obj'>
      <div class='avatar-name'>
        <div class='pending-avatar pending-layer'>
          <%= image_tag User.find(f.id).avatar_thumbnail, class: 'avatar friend_avatar' %>
        </div>
        <div class='pending-name pending-layer'>
          <%= link_to f.name, user_path(f) %>
        </div>
      </div>
      <div class='pending-choices pending-layer'>
        <%= link_to "Add",  friend_requests_path(friend_id: f.id), method: :post, class: 'button is-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_feed.html.erb
<% @user_posts.each do |f|%>
  <div class="message">
    <div class="message-header">
      <div class="message-header-title">
        <%= f.user.name %>
      </div>
      <div class="message-header-date">
        <%= f.created_at.strftime("%Y-%m-%d") %>
      </div>
    </div>
    <div class="message-body">
      <%= f.message %>
      <% if f.image.attached? %>
        <%= image_tag f.image, style: "width: 100%; display: block;"%>
      <% end %>
    </div>
    <div class="message-likes">
      <div class='post-buttons'>
        <% pre_like = f.likes.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
          <%= button_to 'Unlike', user_post_like_path(f.id, pre_like), method: :delete, class: "button is-success" %>
        <% else %>
          <%= button_to 'Like', user_post_likes_path(f.id), method: :post, class: "button is-warning" %>
        <% end %>
        <%= link_to 'comments', user_post_path(f.id), class: "button is-link post-link cmnt-btn" %>
        <% if f.user_id == current_user.id %>
          <%= link_to 'edit', edit_user_post_path(f.id), class: "far fa-edit post-link" %>
          <%= link_to 'delete', user_post_path(f.id), method: :delete, class: "far fa-trash-alt post-link" %>
        <% end %>
      </div>
      <div class='post-stats'>
        <p class="likes-count"><%= f.likes.count %> <%= (f.likes.count) <= 1 ? 'Like' : 'Likes'%></p>
        <p class='comments-count'><%= f.comments.count %> <%= (f.comments.count) <= 1 ? "Comment" : "Comments" %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_search_form.html.erb
<%= form_with(url: search_users_path, method: :get, local: true) do |f| %>
  <%= f.text_field :query, placeholder: "Search Users", class: 'search-box' %>
  <%= button_tag type: 'submit', class: 'search-button' do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>

app/views/users/_searched_users.html.erb
<div class='users-container'>
  <% @searched_users.each do |f| %>
    <div class='pending-user friend-obj'>
      <div class='avatar-name'>
        <div class='pending-avatar pending-layer'>
          <%= image_tag User.find(f.id).avatar_thumbnail, class: 'avatar friend_avatar' %>
        </div>
        <div class='pending-name pending-layer'>
          <%= link_to f.name, user_path(f) %>
        </div>
      </div>
      <div class='pending-choices pending-layer'>
        <% if current_user.friends.where(id: f.id).any? %>
          <%= link_to 'Delete', friends_destroy_path(friend: f.id), method: :delete, class: 'button is-danger' %>
        <% elsif FriendRequest.where(user_id: current_user.id, friend_id: f.id).any? %>
          <p>Request Sent</p>
        <% else %>
          <%= link_to "Add",  friend_requests_path(friend_id: f.id), method: :post, class: 'button is-primary' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_upper_info.html.erb
<div class='upper-info'>
  <div class='avatar'>
    <%= image_tag User.find(params[:id]).avatar_thumbnail, class: 'user_avatar' %>
  </div>
  <div class='user-name'>
    <h1 class='name'><%= @user.name %></h1>
  </div>
  <div class='user-info'>
    <span class='upper-info-item' >
      <i class="fas fa-tint"></i>-type: 
      <%= @user.blood_type %>
    </span>
    <span class='upper-info-item' >
      <i class="fas fa-graduation-cap"></i>: 
      <%= @user.education %></span>
  </div>
  <div class='add-button'>
    <% unless @user == current_user %>
    <% valid_request = FriendRequest.where(friend_id: @user) %>
      <% if valid_request.exists? %>
        <p>Friend request sent</p>
      <% else %>
        <% if @user.friends.include? current_user %>
          <%= link_to 'Unfriend', friends_destroy_path(friend: @user.id), method: :delete, class: 'button is-danger' %>
        <% else %>
          <%= link_to "send friend request",  friend_requests_path(friend_id: @user.id), method: :post, class: 'button is-primary' %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to "edit profile", edit_user_registration_path(@user), class: 'button is-primary' %>
    <% end %>
  </div>
</div>

app/views/users/all_other_users.html.erb
<div class='container friends-container'>
  <div class="column side-bar left-column">
    <%= render 'user_posts/left_bar' %>
  </div>
  <div class='mid-row'>
    <h1 class='center-title'>All Users</h1>
    <% if @current_user.friends.any? %>
      <div class="list-container">
        <%= render 'everyone_else' %>
      </div>
    <% else %>
      <div class='no-request-container'>
        <h2 class='no-requests'>No users here...</h2>
      </div>
    <% end %>
  </div>
  <div class="column right-bar right-column">
    <div class='friend-suggs'>
      <%= render 'user_posts/friend_suggestions' %>
    </div>
    <div class='friends'>
      <%= render 'user_posts/right_bar_friends' %>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<div class='container friends-container'>
  <div class="column side-bar left-column">
    <%= render 'user_posts/left_bar' %>
  </div>
  <div class='mid-row'>
    <h1 class='center-title'>Searched Users</h1>
      <div class="list-container">
        <%= render 'searched_users'%>
      </div>
  </div>
  <div class="column right-bar right-column">
    <div class='friend-suggs'>
      <%= render 'user_posts/friend_suggestions' %>
    </div>
    <div class='friends'>
      <%= render 'user_posts/right_bar_friends' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container'>
  <div class="column side-bar left-column">
    <%= render 'user_posts/left_bar' %>
  </div>
  <div class='column message-feed center-column user-container'>
    <div class='upper-container'>
      <%= render 'upper_info' %>
    </div>
    <div class="feed show-feed">
      <%= render 'feed', user_post: @user_post %>
    </div>
  </div>
  <div class="column right-bar right-column">
    <div class='friend-suggs'>
      <%= render 'user_posts/friend_suggestions' %>
    </div>
    <div class='friends'>
      <%= render 'user_posts/right_bar_friends' %>
    </div>
  </div>
</div>