config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :comments
  get 'friends/index'
  get 'friends/destroy'
  resources :friends, only: [:index, :create, :destroy]
  resources :user_posts
  resources :friend_requests do
    member do
      post :accept
      post :reject
    end
  end
  resources :user_posts do
    resources :comments
    resources :likes
  end
  match 'users/:id' => 'users#show', :as => :user, :via => :get
  match 'pending_requests' => 'friend_requests#index', :as => :pending_requests, :via => :get
  get 'all_users' => 'users#all_other_users'
  get 'search_users' => 'users#search'
  # edit user profile
  # match 'users/edit/:id' => 'users#edit', :as => :edit_profile, :via => :get

  # match 'friends' => 'friends#index', :as => :friends, :via => :get

  root 'user_posts#index'
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  validate :not_self
  validate :not_friends
  # validate :not_pending
  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  private

  def not_self
    errors.add(:friend, "can't be the same as user") if user == friend
  end

  def not_friends
    errors.add(:friend, 'is already a friend') if user.friends.include?(friend)
  end

  # def not_pending
  #   errors.add(:friend, 'already requested friendship') if user.pending_friends.include?(friend)
  # end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  def index
    @incoming = FriendRequest.where(friend: current_user)
    @outgoing = current_user.friend_requests
  end

  def create
    friend = User.find(params[:friend_id])
    @friend_request = current_user.friend_requests.create(friend: friend)
    if @friend_request.save
      flash[:notice] = "Friend request sent"
      redirect_to user_path(friend)
    else
      render json: @friend_request.errors, status: :unprocessable_entity
    end
  end

  def accept
    friend = User.find(params[:id])
    current_user.friends << friend
    flash[:notice] = "Friend request accepted"
    redirect_back fallback_location: root_path
    destroy
  end

  def reject
    flash[:alert] = "Friend request rejected"
    redirect_back fallback_location: root_path
    destroy
  end

  def destroy
    @friend_request = FriendRequest.where(user: params[:id], friend: current_user).first
    if @friend_request.present?
      @friend_request.destroy
    end
  end

  private

  def friend_request_params
    params.require(:friend_request).permit(:friend_id, :user_id)
  end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_pending_friends.html.erb
<div class='users-container'>
  <% @incoming.each do |f| %>
    <div class='pending-user friend-obj'>
      <div class='avatar-name'>
        <div class='pending-avatar pending-layer'>
          <%= image_tag User.find(f.user_id).avatar_thumbnail, class: 'avatar friend_avatar' %>
        </div>
        <div class='pending-name pending-layer'>
          <%= link_to User.find(f.user_id).name, user_path(f.user_id) %>
        </div>
      </div>
      <div class='pending-choices pending-layer'>
        <span><%= link_to "Accept", accept_friend_request_path(f.user_id), method: :post, class: 'button is-primary' %></span>
        <span><%= link_to "Reject", reject_friend_request_path(f.user_id), method: :post, class: 'button is-danger'  %></span>
      </div>
    </div>
  <% end %>
</div>

app/views/friend_requests/index.html.erb
<div class='container pending-container'>
  <div class="column side-bar left-column">
    <%= render 'user_posts/left_bar' %>
  </div>
  <div class='mid-row'>
    <h1 class='center-title'>Pending Requests</h1>
     <% if @incoming.any? %> 
      <div class='list-container'>
      <%= render 'pending_friends' %>
      </div>
    <% else %>
      <div class='no-request-container'>
        <h2 class='no-requests'>No Friend Requests At This Time.</h2>
      </div>
    <% end %>
  </div>
  <div class="column right-bar right-column">
    <div class='friend-suggs'>
      <%= render 'user_posts/friend_suggestions' %>
    </div>
    <div class='friends'>
      <%= render 'user_posts/right_bar_friends' %>
    </div>
  </div>
</div>